.global reset, nmi
.global music_start
.global level_name
.global level_title
.global label_de0d
.global ram_05, ram_5b, ram_11, ram_12, ram_86, player_velocity, ram_04, label_d8b7, label_c35a, label_c236, label_db8e
.global player_fall_state, label_d5c3, label_d5ed, nesmus_shut_up, label_e7f4, label_c3eb, label_da95, label_cab7
.global i_frames, label_c9e2, player_position_y_again, ram_0b, label_db61, label_e816, label_e679, player_health, label_c24e
.global label_e8ed, label_d2bb, label_c7ec, label_cabb, get_controller_buttons, label_dc71, player_lives, label_e6eb, ram_07
.global label_c26a, label_c1c2, ram_06, label_dc26, label_dbda, label_f5dd, label_e5eb
.global temp, ram_87, idx
